const countries = {
  "Global": {
    "NewConfirmed": 85420,
    "TotalConfirmed": 4333463,
    "NewDeaths": 5803,
    "TotalDeaths": 297231,
    "NewRecovered": 39651,
    "TotalRecovered": 1495209
  },
  "Countries": [
    {
      "Country": "Afghanistan",
      "CountryCode": "AF",
      "Slug": "afghanistan",
      "NewConfirmed": 276,
      "TotalConfirmed": 4963,
      "NewDeaths": 5,
      "TotalDeaths": 127,
      "NewRecovered": 52,
      "TotalRecovered": 610,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Albania",
      "CountryCode": "AL",
      "Slug": "albania",
      "NewConfirmed": 4,
      "TotalConfirmed": 876,
      "NewDeaths": 0,
      "TotalDeaths": 31,
      "NewRecovered": 28,
      "TotalRecovered": 682,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Algeria",
      "CountryCode": "DZ",
      "Slug": "algeria",
      "NewConfirmed": 176,
      "TotalConfirmed": 6067,
      "NewDeaths": 8,
      "TotalDeaths": 515,
      "NewRecovered": 157,
      "TotalRecovered": 2998,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Andorra",
      "CountryCode": "AD",
      "Slug": "andorra",
      "NewConfirmed": 3,
      "TotalConfirmed": 758,
      "NewDeaths": 0,
      "TotalDeaths": 48,
      "NewRecovered": 18,
      "TotalRecovered": 568,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Angola",
      "CountryCode": "AO",
      "Slug": "angola",
      "NewConfirmed": 0,
      "TotalConfirmed": 45,
      "NewDeaths": 0,
      "TotalDeaths": 2,
      "NewRecovered": 0,
      "TotalRecovered": 13,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Antigua and Barbuda",
      "CountryCode": "AG",
      "Slug": "antigua-and-barbuda",
      "NewConfirmed": 0,
      "TotalConfirmed": 25,
      "NewDeaths": 0,
      "TotalDeaths": 3,
      "NewRecovered": 0,
      "TotalRecovered": 19,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Argentina",
      "CountryCode": "AR",
      "Slug": "argentina",
      "NewConfirmed": 285,
      "TotalConfirmed": 6563,
      "NewDeaths": 5,
      "TotalDeaths": 319,
      "NewRecovered": 25,
      "TotalRecovered": 1862,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Armenia",
      "CountryCode": "AM",
      "Slug": "armenia",
      "NewConfirmed": 146,
      "TotalConfirmed": 3538,
      "NewDeaths": 1,
      "TotalDeaths": 47,
      "NewRecovered": 71,
      "TotalRecovered": 1430,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Australia",
      "CountryCode": "AU",
      "Slug": "australia",
      "NewConfirmed": 10,
      "TotalConfirmed": 6980,
      "NewDeaths": 1,
      "TotalDeaths": 98,
      "NewRecovered": 57,
      "TotalRecovered": 6270,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Austria",
      "CountryCode": "AT",
      "Slug": "austria",
      "NewConfirmed": 79,
      "TotalConfirmed": 15961,
      "NewDeaths": 3,
      "TotalDeaths": 623,
      "NewRecovered": 87,
      "TotalRecovered": 14148,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Azerbaijan",
      "CountryCode": "AZ",
      "Slug": "azerbaijan",
      "NewConfirmed": 104,
      "TotalConfirmed": 2693,
      "NewDeaths": 1,
      "TotalDeaths": 33,
      "NewRecovered": 0,
      "TotalRecovered": 1680,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Bahamas",
      "CountryCode": "BS",
      "Slug": "bahamas",
      "NewConfirmed": 0,
      "TotalConfirmed": 93,
      "NewDeaths": 0,
      "TotalDeaths": 11,
      "NewRecovered": 0,
      "TotalRecovered": 39,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Bahrain",
      "CountryCode": "BH",
      "Slug": "bahrain",
      "NewConfirmed": 295,
      "TotalConfirmed": 5531,
      "NewDeaths": 1,
      "TotalDeaths": 9,
      "NewRecovered": 40,
      "TotalRecovered": 2192,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Bangladesh",
      "CountryCode": "BD",
      "Slug": "bangladesh",
      "NewConfirmed": 969,
      "TotalConfirmed": 16660,
      "NewDeaths": 11,
      "TotalDeaths": 250,
      "NewRecovered": 245,
      "TotalRecovered": 3147,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Barbados",
      "CountryCode": "BB",
      "Slug": "barbados",
      "NewConfirmed": 1,
      "TotalConfirmed": 85,
      "NewDeaths": 0,
      "TotalDeaths": 7,
      "NewRecovered": 0,
      "TotalRecovered": 57,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Belarus",
      "CountryCode": "BY",
      "Slug": "belarus",
      "NewConfirmed": 967,
      "TotalConfirmed": 24873,
      "NewDeaths": 7,
      "TotalDeaths": 142,
      "NewRecovered": 443,
      "TotalRecovered": 6974,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Belgium",
      "CountryCode": "BE",
      "Slug": "belgium",
      "NewConfirmed": 330,
      "TotalConfirmed": 53779,
      "NewDeaths": 54,
      "TotalDeaths": 8761,
      "NewRecovered": 35,
      "TotalRecovered": 13732,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Belize",
      "CountryCode": "BZ",
      "Slug": "belize",
      "NewConfirmed": 0,
      "TotalConfirmed": 18,
      "NewDeaths": 0,
      "TotalDeaths": 2,
      "NewRecovered": 0,
      "TotalRecovered": 16,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Benin",
      "CountryCode": "BJ",
      "Slug": "benin",
      "NewConfirmed": 8,
      "TotalConfirmed": 327,
      "NewDeaths": 0,
      "TotalDeaths": 2,
      "NewRecovered": 14,
      "TotalRecovered": 76,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Bhutan",
      "CountryCode": "BT",
      "Slug": "bhutan",
      "NewConfirmed": 2,
      "TotalConfirmed": 11,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 5,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Bolivia",
      "CountryCode": "BO",
      "Slug": "bolivia",
      "NewConfirmed": 133,
      "TotalConfirmed": 2964,
      "NewDeaths": 6,
      "TotalDeaths": 128,
      "NewRecovered": 14,
      "TotalRecovered": 313,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Bosnia and Herzegovina",
      "CountryCode": "BA",
      "Slug": "bosnia-and-herzegovina",
      "NewConfirmed": 17,
      "TotalConfirmed": 2158,
      "NewDeaths": 4,
      "TotalDeaths": 117,
      "NewRecovered": 54,
      "TotalRecovered": 1168,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Botswana",
      "CountryCode": "BW",
      "Slug": "botswana",
      "NewConfirmed": 0,
      "TotalConfirmed": 24,
      "NewDeaths": 0,
      "TotalDeaths": 1,
      "NewRecovered": 5,
      "TotalRecovered": 17,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Brazil",
      "CountryCode": "BR",
      "Slug": "brazil",
      "NewConfirmed": 8620,
      "TotalConfirmed": 178214,
      "NewDeaths": 808,
      "TotalDeaths": 12461,
      "NewRecovered": 5213,
      "TotalRecovered": 72597,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Brunei Darussalam",
      "CountryCode": "BN",
      "Slug": "brunei",
      "NewConfirmed": 0,
      "TotalConfirmed": 141,
      "NewDeaths": 0,
      "TotalDeaths": 1,
      "NewRecovered": 0,
      "TotalRecovered": 134,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Bulgaria",
      "CountryCode": "BG",
      "Slug": "bulgaria",
      "NewConfirmed": 33,
      "TotalConfirmed": 2023,
      "NewDeaths": 2,
      "TotalDeaths": 95,
      "NewRecovered": 15,
      "TotalRecovered": 476,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Burkina Faso",
      "CountryCode": "BF",
      "Slug": "burkina-faso",
      "NewConfirmed": 6,
      "TotalConfirmed": 766,
      "NewDeaths": 1,
      "TotalDeaths": 51,
      "NewRecovered": 4,
      "TotalRecovered": 588,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Burundi",
      "CountryCode": "BI",
      "Slug": "burundi",
      "NewConfirmed": 0,
      "TotalConfirmed": 15,
      "NewDeaths": 0,
      "TotalDeaths": 1,
      "NewRecovered": 0,
      "TotalRecovered": 7,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Cambodia",
      "CountryCode": "KH",
      "Slug": "cambodia",
      "NewConfirmed": 0,
      "TotalConfirmed": 122,
      "NewDeaths": 0,
      "TotalDeaths": 0,
      "NewRecovered": 0,
      "TotalRecovered": 121,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Cameroon",
      "CountryCode": "CM",
      "Slug": "cameroon",
      "NewConfirmed": 0,
      "TotalConfirmed": 2689,
      "NewDeaths": 0,
      "TotalDeaths": 125,
      "NewRecovered": 0,
      "TotalRecovered": 1524,
      "Date": "2020-05-13T20:24:25Z"
    },
    {
      "Country": "Canada",
      "CountryCode": "CA",
      "Slug": "canada",
      "NewConfirmed": 2310,
      "TotalConfirmed": 144836,
      "NewDeaths": 370,
      "TotalDeaths": 10598,
      "NewRecovered": 1048,
      "TotalRecovered": 34055,
      "Date": "2020-05-13T20:24:25Z"
    }
]
};